### 1.2.1 Пример
Создать массив 5x2. Создать массив 5x2. Вывести все значения массива, значение элемента с индексом (3,1) и второй столбец. Индексация начинается с нуля.

In [73]:
import numpy as np
x = np.array([[1,2], [3,4], [5,6], [7,8], [9,10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


### 1.2.2 Пример

In [74]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


### 1.2.3 Пример
Создать массив 10x10 со случайными значениями, найти минимум, максимум и среднее значение

In [75]:
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.011020240557171102 0.9863851958609133 0.4845999409505751


### 1.2.4 Пример
Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице местами.

In [76]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### 1.2.5 Пример
Выяснить результат следующих выражений

In [77]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


### 1.2.6 Пример
Отсортировать массив

In [78]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


### 1.3.1 Задание
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами

In [79]:
A = np.full((8,8), 1)
A[1::2,::2] = 0
A[0::2,1::2] = 0
print(A)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


### 1.3.2 Задание
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arrange

In [80]:
A = np.full((5,5), 0)
A[0:5] = np.arange(5)
print(A)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 1.3.3 Задание
Создать массив 3x3x3 со случайными значениями

In [81]:
A = np.random.random((3,3,3))
print(A)

[[[0.69100095 0.31398088 0.21691426]
  [0.27636905 0.68856637 0.73704699]
  [0.67139143 0.47341395 0.85333493]]

 [[0.79980527 0.05653877 0.70026025]
  [0.12270881 0.52542882 0.99399134]
  [0.27217782 0.61114403 0.12693857]]

 [[0.85591325 0.61508722 0.56228401]
  [0.63125904 0.21348835 0.82246874]
  [0.11970447 0.08231968 0.76406253]]]


### 1.3.4 Задание
Создать матрицу с 0 внутри, и 1 на границах

In [82]:
b = np.ones((5, 5))
b[1:-1, 1:-1] = 0
print(b)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### 1.3.5 Задание
Создайте массив и отсортируйте его по убыванию.

In [83]:
a = np.arange(1, 8)
print(-np.sort(-a))

[7 6 5 4 3 2 1]


### ! 1.3.6 Задание
Создайте матрицу, выведите ее форму, размер и размерность

In [84]:
A = np.zeros((5, 10))

print(A)
print(np.shape(A))
print(np.size(A))
print(np.ndim(A))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(5, 10)
50
2


### 2.2.1 Пример
Создать Series из списка Python, словаря Python, и массива Numpy (установить буквенные метки для последнего)

In [85]:
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


### 2.2.2 Пример
Дано два Series. Напечатать их первые элементы и все элементы после третьего (во втором фрейме)

In [86]:
s1 = pd.Series([1,2,3,4,5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


### 2.2.3 Пример
Создайте новый фрейм данных

In [87]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe['Возраст'] = [38, 25]
dataframe['Водитель'] = [True, False]
dataframe

Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

### 2.2.4 Пример
Загрузите фрейм данных по ссылке

In [88]:
# Создать URL-адрес
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/f0ccab6a7ceafdff780052166fb6fab3311398eb/titanic.csv'
# Загрузить данные
dataframe = pd.read_csv(url)
# Показать пять строк
dataframe.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

### 2.2.5 Пример
Пронализировать характеристики фрейма данных

In [89]:
dataframe.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [90]:
dataframe.tail(3)

PassengerId  Survived  Pclass                                      Name  \
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [91]:
dataframe.shape

(891, 12)

In [92]:
dataframe.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

### 2.2.6 Пример
Выберите индивидуальные данные или срезы фрейма данных

In [93]:
dataframe.iloc[1:4]

PassengerId  Survived  Pclass  \
1            2         1       1   
2            3         1       3   
3            4         1       1   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   

   Parch            Ticket     Fare Cabin Embarked  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S

### 2.2.7 Пример
Требуется отобрать строки фрейма данных на основе некоторого условия. Необходимо сформировать новый фрейм данных из пассажиров первого класса.

In [94]:
dataframe[dataframe['Pclass'] == 1].head(2)

PassengerId  Survived  Pclass  \
1            2         1       1   
3            4         1       1   

                                                Name     Sex   Age  SibSp  \
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   

   Parch    Ticket     Fare Cabin Embarked  
1      0  PC 17599  71.2833   C85        C  
3      0    113803  53.1000  C123        S

### 2.3.1 Задача
Найдитн евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу.

In [95]:
a = np.array((1, 0, 3))
b = np.array((1, 2, 3))

sq = np.square(a - b)
_sum = np.sum(sq)

print(np.sqrt(_sum))

2.0


### 2.3.2 Задача
Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных

In [96]:
dataframe=pd.read_csv("bacteria_list_200.csv")
dataframe.head()

Name              Family  \
0           Escherichia coli  Enterobacteriaceae   
1      Staphylococcus aureus   Staphylococcaceae   
2  Lactobacillus acidophilus    Lactobacillaceae   
3          Bacillus subtilis         Bacillaceae   
4      Clostridium botulinum      Clostridiaceae   

                     Where Found Harmful to Humans  
0               Intestinal tract               Yes  
1           Skin, nasal passages               Yes  
2        Human mouth & intestine                No  
3                           Soil                No  
4  Soil, improperly canned foods               Yes

### 2.3.3 Задача
Проделайте с получившемся из предыдущего задания фреймом данных те же действия, что и в примерах 2.2.5-2.2.7.

In [97]:
dataframe=pd.read_csv("bacteria_list_200.csv")
dataframe.head(10)

Name              Family  \
0            Escherichia coli  Enterobacteriaceae   
1       Staphylococcus aureus   Staphylococcaceae   
2   Lactobacillus acidophilus    Lactobacillaceae   
3           Bacillus subtilis         Bacillaceae   
4       Clostridium botulinum      Clostridiaceae   
5    Streptococcus pneumoniae    Streptococcaceae   
6      Pseudomonas aeruginosa    Pseudomonadaceae   
7  Mycobacterium tuberculosis    Mycobacteriaceae   
8             Vibrio cholerae        Vibrionaceae   
9         Salmonella enterica  Enterobacteriaceae   

                     Where Found Harmful to Humans  
0               Intestinal tract               Yes  
1           Skin, nasal passages               Yes  
2        Human mouth & intestine                No  
3                           Soil                No  
4  Soil, improperly canned foods               Yes  
5         Throat, nasal passages               Yes  
6        Soil, water, skin flora               Yes  
7                          Lungs               Yes  
8             Contaminated water               Yes  
9               Intestinal tract               Yes

In [98]:
dataframe.tail(3)

Name             Family          Where Found  \
196  Tepidimonas arfidensis     Comamonadaceae      Thermal springs   
197    Ulvibacter litoralis  Flavobacteriaceae  Marine environments   
198       Vibrio vulnificus       Vibrionaceae  Marine environments   

    Harmful to Humans  
196                No  
197                No  
198               Yes

In [99]:
dataframe.shape

(199, 4)

In [100]:
dataframe.describe()

Name              Family Where Found  \
count                     199                 199         199   
unique                    194                  93         120   
top     Gardnerella vaginalis  Enterobacteriaceae        Soil   
freq                        2                  21          17   

       Harmful to Humans  
count                199  
unique                 3  
top                   No  
freq                 102

In [101]:
dataframe.iloc[1:4]

Name             Family              Where Found  \
1      Staphylococcus aureus  Staphylococcaceae     Skin, nasal passages   
2  Lactobacillus acidophilus   Lactobacillaceae  Human mouth & intestine   
3          Bacillus subtilis        Bacillaceae                     Soil   

  Harmful to Humans  
1               Yes  
2                No  
3                No

In [102]:
dataframe[dataframe['Harmful to Humans'] == 'Yes'].head(5)

Name              Family  \
0          Escherichia coli  Enterobacteriaceae   
1     Staphylococcus aureus   Staphylococcaceae   
4     Clostridium botulinum      Clostridiaceae   
5  Streptococcus pneumoniae    Streptococcaceae   
6    Pseudomonas aeruginosa    Pseudomonadaceae   

                     Where Found Harmful to Humans  
0               Intestinal tract               Yes  
1           Skin, nasal passages               Yes  
4  Soil, improperly canned foods               Yes  
5         Throat, nasal passages               Yes  
6        Soil, water, skin flora               Yes

### 3.2.1 Пример
Прошкалируйте числовой признак в диапазон между двумя значениями.

In [103]:
from sklearn import preprocessing

# Создать признак
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
# Создать шкалировщик
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))

# Прошкалировать признак
scaled_feature = minmax_scale.fit_transform(feature)

# Показать прошкалированный признак
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

### 3.2.2 Пример
Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное отклонение 1

In [104]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])

# Создать шкалировщик
scaler = preprocessing.StandardScaler()
# Преобразовать признак
standardized = scaler.fit_transform(x)
# Показать признак
standardized


array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

In [105]:
print("Среднее:", round(standardized.mean()))
print("Стандартное отклонение:", standardized.std())

Среднее: 0
Стандартное отклонение: 1.0


### 3.2.3 Пример
Дан фрейм данных. Необходимо масштабировать его числовые столбцы.

In [106]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                       'B':[103.02,107.26,110.35,114.23,114.68],
                       'C':['big','small','big','small','small']})

dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

### 3.3.2 Задание
Загрузить фрейм данных по ссылке. Необходимо выполнить нормализацию первого числового признака (sepal_length_cm) с использованием минимаксного преобразования, а второго (sepal_width_cm) с задействованием z-масштабирования.

In [107]:
from sklearn.preprocessing import StandardScaler
dataframe = pd.read_csv('https://raw.githubusercontent.com/akmand/datasets/master/iris.csv')

dataframe[['sepal_length_cm']] = MinMaxScaler().fit_transform(dataframe[['sepal_length_cm']])
dataframe[['sepal_width_cm']] = StandardScaler().fit_transform(dataframe[['sepal_width_cm']])
dataframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]